import { expect, test } from '@playwright/test';
import fixture from '../lib/demo-data.json';

test('real signup, HttpOnly session, protected training, logout and login restore progress', async ({ page, context }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem('ecg-user', JSON.stringify({ id: 'u-teacher-1', name: 'Professor falso', role: 'teacher' })));
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Quero criar uma conta', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Quero criar uma conta', exact: true }).click();
  const email = `browser-${Date.now()}@example.org`, password = 'Frase longa para teste no navegador!';
  await page.getByLabel('E-mail', { exact: true }).fill(email);
  await page.getByLabel('Nome', { exact: true }).fill('Aluno do navegador');
  await page.getByLabel('Senha', { exact: true }).fill(password);
  const questionResponse = page.waitForResponse((response) => response.url().includes('/training/question') && response.status() === 200);
  await page.getByRole('button', { name: 'Criar conta de aluno', exact: true }).click();
  const question = await (await questionResponse).json();
  expect(question.question.correctAnswer).toBeUndefined();
  expect(question.caseData.diagnosis).toBeUndefined();
  const expected = fixture.questions.find((item) => item.id === question.question.id)!;
  const caseTitle = fixture.cases.find((item) => item.id === question.caseData.id)!.title;
  const wrongOption = question.question.options.find((option: string) => option !== expected.correctAnswer);
  await expect(page.getByText('Perfil aluno', { exact: true })).toBeVisible();
  const cookie = (await context.cookies('http://localhost:4000/api/auth/me')).find((c) => c.name === 'ecg_session');
  expect(cookie?.httpOnly).toBe(true); expect(cookie?.sameSite).toBe('Strict');
  await page.getByRole('button', { name: 'Banco de casos', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Cadastrar caso', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Treino', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Interprete o ECG', exact: true })).toBeVisible();
  await page.getByRole('button', { name: wrongOption, exact: true }).click();
  await page.getByRole('button', { name: 'Responder', exact: true }).click();
  await expect(page.getByText('Resposta incorreta', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: caseTitle, exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Meu progresso', exact: true }).click();
  await expect(page.getByText('1 tentativas', { exact: false }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Encerrar sessão', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Acessar', exact: true })).toBeVisible();
  await page.getByLabel('E-mail', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill('Uma senha errada para testar!');
  await page.getByRole('button', { name: 'Acessar', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('E-mail ou senha inválidos');
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Acessar', exact: true }).click();
  await expect(page.getByText('Perfil aluno', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Meu progresso', exact: true }).click();
  await expect(page.getByText('1 tentativas', { exact: false }).first()).toBeVisible();
  expect(errors).toEqual([]);
});
